import clsx from 'clsx';
import type { Metadata } from 'next';
import { JetBrains_Mono, Noto_Sans_JP } from 'next/font/google';

import './globals.css';
import Header from '@/components/Header';

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jetbrainsMono',
});

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className={clsx(jetbrainsMono.variable, notoSansJP.variable)}>
        <Header />
        {children}
      </body>
    </html>
  );
}
